remote:
  base_dir: mnist_test

files:
  push:
    - train.py
    - requirements.txt
  fetch:                             # optional; if omitted, fetch entire run dir
    - "{run_dir}/model.pth"
    - "{run_dir}/log.txt"

slurm:
  directives: |
    #SBATCH --job-name={base_dir}
    #SBATCH --partition=gpu
    #SBATCH --time=00:10:00
    #SBATCH --cpus-per-gpu=4
    #SBATCH --nodes=1
    #SBATCH --gres=gpu:1
    #SBATCH --mem=16G

run:
  command: |
    source venv/bin/activate
    python train.py --lr {lr} --epochs {epochs} --save_model "{run_dir}/model.pth" --log_file "{run_dir}/log.txt"
  grid:
    lr: [0.01, 0.001]
    epochs: [2, 5]

  # OR YOU CAN DO:
  # experiments:
  #   - { lr: 0.1, epochs: 1 }
  #   - { lr: 0.001, epochs: 10 }